version: '3.8'
services:
  katalog-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: katalog-service
    ports:
      - "8000:8000"
    environment:
      - APP_ENV=local
      - DB_CONNECTION=sqlite
      - IAE_API_KEY=102022400192
      - L5_SWAGGER_GENERATE_ALWAYS=true
    restart: unless-stopped